// Crew password check for web co-op. Generated by tools/set-password.mjs;
// only the salted PBKDF2-SHA256 hash is stored here, never the password.
export const CREW_KEY = { salt: 'wide-load:e50b159716d86c6d', iterations: 150000, hash: '6feb3cdfb5dbcfefad464a2d4d2a2f1a655c8df98184382f64186f136b0bec72' };
